services:
  web:
    image: odoo:14.0
    depends_on:
      - db
    ports:
      - "80:8069"
    volumes:
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
